### ISSUE TITLE
yet.. another request of VLESS[Feature] 

### ISSUE THREAD

**Issue by mvccn** [Dreamacro/clash#1670]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

I have seen other vless request here, but they were largely ignored so far. Can we please add VLESS, so far other major v2ray clients all support it. If this is not in the roadmap,  can we elaborate why? Many thanks!

**Comment by Warden630** [comment]
I have been using Trojan for more than a year, but it's been detected by the GFW recently. And some of my VPS port 443 has been blocked. 
Will Clash support Xray?

**Comment by danielfbm** [comment]
VLESS + XTLS +1 here, it provides a more stable protocol against GFW. I :heart: Clash, but at some specific times in the mainland, vmess is easily detected making access unstable.

**Comment by hfdem** [comment]
想要
1.服务端使用xray的情况下实现fullcone
2.客户端支持VLESS、xtls

**Comment by OneHappyForever** [comment]
> I don't know if the latest version of the protocol currently has full support for UDP, but at the beginning, like vmess, had incomplete support for UDP.
> 
> On the other hand, v2fly intends to deprecate vless (not xray) and there is no maintainer on vless. IMO, there is no essential difference between vless and trojan (even trojan supports full UDP). So I don't understand why you guys love vless so much.

Trojan hasn’t been updated for a long time either, but Clash still supports it, so that should not be a reason. Also, the Xray repo is still updated. Vless and xtls has full UDP support. 

Please point to where v2fly says they are going to deprecate VLESS, I could not find this anywhere, and VLESS is in their docs as well. At the very least VLESS should be supported.

Why we love VLESS so much: because almost all apps other than clash already support it. Also, VLESS+ TLS is not blocked nearly as much vs VMESS. VMESS + TLS has a lot of encryption and RTTs and is heavy. Xray is updated vs Trojan.

**Comment by layou233** [comment]
> I don't know if the latest version of the protocol currently has full support for UDP, but at the beginning, like vmess, had incomplete support for UDP.
> 
> On the other hand, v2fly intends to deprecate vless (not xray) and there is no maintainer on vless. IMO, there is no essential difference between vless and trojan (even trojan supports full UDP). So I don't understand why you guys love vless so much.

Now we can make up our mind to realize VLESS. He has nearly solved almost all problems and played better than VMess.  
I have tried VLESS XTLS with `xtls-rprx-direct` for days, I can say without doubt that it is faster than any other protocols we have met, **EVEN SOCKS** (by testing speedtest.net).  
If you are running Xray-core as client on Linux (include Android), `xtls-rprx-splice` can make a even faster experience than above.  
XTLS means less encryption, making network transmission faster and more power efficient. ([also a small fault](https://github.com/XTLS/Xray-core/discussions/593))
VLESS is now maintained by XTLS (Xray-core) team. They are active on developing.  
For UDP, they impl the XUDP, which makes VLESS to be Fullcone and also fixed UDP problems for VMess.  
Of course, I'm not deifying VLESS. VLESS still has shortcomings and room for development, but I think it can be competent for the production environment.

**Comment by layou233** [comment]
> > I don't know if the latest version of the protocol currently has full support for UDP, but at the beginning, like vmess, had incomplete support for UDP.
> > On the other hand, v2fly intends to deprecate vless (not xray) and there is no maintainer on vless. IMO, there is no essential difference between vless and trojan (even trojan supports full UDP). So I don't understand why you guys love vless so much.
> 
> Trojan hasn’t been updated for a long time either, but Clash still supports it, so that should not be a reason. Also, the Xray repo is still updated. Vless and xtls has full UDP support.
> 
> Please point to where v2fly says they are going to deprecate VLESS, I could not find this anywhere, and VLESS is in their docs as well. At the very least VLESS should be supported.
> 
> Why we love VLESS so much: because almost all apps other than clash already support it. Also, VLESS+ TLS is not blocked nearly as much vs VMESS. VMESS + TLS has a lot of encryption and RTTs and is heavy. Xray is updated vs Trojan.

In fact, not `deprecate`.  
https://github.com/XTLS/Go/issues/9  
https://github.com/v2ray/v2ray-core/issues/2789#issuecomment-728920409  
The world famous negotiation (or a war) for XTLS on its license problem, resulted as the removing of XTLS.  
Even if xtls later switched to MPL license, v2ray had removed xtls before and had no intention to resume use, so the Xray project began.  
Since Xray was separated from v2ray, the focus of VLESS has shifted to Xray, because RPRX is the main designer and maintainer of VLESS.  
Therefore, maybe the only thing is that VLESS is treated disequally between v2ray and Xray.
