### ISSUE TITLE
[Feature] 能否支持vless协议

### ISSUE THREAD

**Issue by MoeCinnamo** [Dreamacro/clash#2455]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

目前，我尝试了多次，发现它并不能支持vless协议

请问，能否真正实现支持vless协议？

**Comment by oftenhamed** [comment]
Hi, vless is supported and working on iPhone client app, but Android client app does not support vless.

I need it because only vless + ws is working fine in my country(Iran) and my friends who have Android phones can not use clash and are connected via V2rayNG instead.

also I have a question if you could help me, I do not really understand how the Tolerance and Interval in the yaml config file work.
could you please help me understand it?

  - name: ♻️ Auto-Select
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - UK-trojan
      - IR-trojan

**Comment by k-ykl** [comment]
You can start a vless service alone with socks5 support , eg. Termux .  then the clash connect this socks5 port . This workaround can make it compatible to all protocols.

**Comment by BirkhoffLee** [comment]
https://github.com/Dreamacro/clash/issues/1185
