### ISSUE TITLE
[Feature] 能否在load-balance、url-test、fallback等策略组类型添加可自定义的time-out参数？

### ISSUE THREAD

**Issue by psikent** [Dreamacro/clash#2456]
### Verify steps

- [X]  我已经在 [Issue Tracker](……/) 中找过我要提出的请求 I have searched on the [issue tracker](……/) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://github.com/Dreamacro/clash/wiki/) 并无法自行解决问题 I have read the [documentation](https://github.com/Dreamacro/clash/wiki/) and was unable to solve the issue. 

### Description

time-out参数：测试超时时间，测试超时的节点在本轮测试有效期内不被使用且测试中断

**Comment by imyhxy** [comment]
是的，有时会用Fallback策略让Clash适应不同的使用地点，但是Fallback的超时太慢了，开机后可能要一两分钟才能跳过那个不能连接的节点。

**Comment by SSgumS** [comment]
Hello

In situations where Clash is used, servers might not always be reliable; this assumption is trivial. These issues are especially problematic for groups using the load-balance type. In Iran, some servers don't connect at all. Although some servers can be connected, their pings vary greatly and they are relatively slow; from 200ms to 2000ms. These servers are problematic in the load-balance type because they are wrongly selected as live servers and as a result, the user experience is poor.

I think some timeout parameters should be configurable for automatic groups like load-balance; like `timeout-limit`, `fail-timeout`, `max-fails`, etc.

- `timeout-limit`: If a server doesn't pass the test in `timeout-limit` seconds, it will be considered dead and the `fails` count is incremented.

- `fail-timeout`: how long a server should be marked as dead.

- `max-fails`: how many times a server should fail in a `fail-timeout` period to be marked as dead.

Due to Iran's highly complicated network conditions, the current load-balance mechanism is useless. The very purpose of Clash's existence is to be used in countries like these, so it should be prone to such conditions.

Hope to see this feature soon!

**Comment by Artoria2e5** [comment]
目前最容易改的是 timeout-limit，默认是 5 秒

https://github.com/Dreamacro/clash/blob/4d66da2277ddaf41f83bd889b064c0a584f7a8ad/adapter/provider/healthcheck.go#LL66C61-L66C82

https://github.com/Dreamacro/clash/blob/4d66da2277ddaf41f83bd889b064c0a584f7a8ad/adapter/provider/healthcheck.go#L14

当然建议是到时候用毫秒

* * *
fail-timeout 和 max-fails 需要加额外的逻辑，这个给 struct 加一个成员就行

**Comment by Artoria2e5** [comment]
stale bot 在哪都是毒瘤
