### ISSUE TITLE
[Feature]不支持v2ray的vmess + TCP +TLS的连接吗

### ISSUE THREAD

**Issue by orwithout** [Dreamacro/clash#741]
我的v2ray服务器上配置了入口：
"inbounds":
{
			"tag": "in443",
			"port": 443,
			"protocol": "vmess",
			"settings": {
				"clients": [
					{
						"id": "uuid",
						"security": "auto",
						"alterId": 18
					}
				]
			},
			"streamSettings": {
				"network": "tcp",
				"security": "tls",
				"tcpSettings": {},
				"tlsSettings": {
					"certificates": [
						{
							"certificateFile": "/etc/v2ray/tls.crt",
							"keyFile": "/etc/v2ray/tls.key"
						}
					]
				}
			}
		},

使用v2ray的core可以连接
clash的vmess接口、无论如何配置都没有一次能连通。我现在在v2ray前面加了个nginx的代理后,clash
做客户端才是ok的了。所以我敢说clash真的不支持v2ray的vmess+tcp+TLS的连接类型。

**Comment by zhuohan** [comment]
支持啊我用的好好的，你自己检查一下配置吧

**Comment by phlinhng** [comment]
你在 clash 问问题却不附上 clash 的配置？

**Comment by matreex** [comment]
[https://imgbox.com/eKIPK6C8](https://images2.imgbox.com/83/3d/eKIPK6C8_o.png)
`port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
  - name: vmess
    type: vmess
    mux: false
    skip-cert-verify: false
    server: tacotasty.tk
    port: 443
    uuid: df4fccc8-b396-11ea-a1f2-560002d8a70d
    alterId: "46"
    cipher: auto
    udp: true
    tls: true
#   tls-hostname:
    network: ws
    ws-path: /ZWPGNL9M/
    ws-headers:
      Host: tacotasty.tk
Proxy Group:
  - name: "WHiTelist"
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 200
    proxies:
     - vmess
  - name: "blaCKlist"
    type: select
    proxies:
      - "REJECT"
      - "DIRECT"
##
Rule:
# TRUE
  - DOMAIN-KEYWORD,amazon,WHiTelist
  - DOMAIN-KEYWORD,blogspot,WHiTelist
  - DOMAIN-KEYWORD,dropbox,WHiTelist
  - DOMAIN-KEYWORD,facebook,WHiTelist
  - DOMAIN-KEYWORD,gmail,WHiTelist
  - DOMAIN-KEYWORD,google,WHiTelist
  - DOMAIN-KEYWORD,instagram,WHiTelist
  - DOMAIN-KEYWORD,twitter,WHiTelist
  - DOMAIN-KEYWORD,whatsapp,WHiTelist
  - DOMAIN-KEYWORD,youtube,WHiTelist
  - DOMAIN-SUFFIX,fb.me,WHiTelist
  - DOMAIN-SUFFIX,fbcdn.net,WHiTelist
  - DOMAIN-SUFFIX,twimg.com,WHiTelist
  - DOMAIN-SUFFIX,t.me,WHiTelist
  - DOMAIN-SUFFIX,youtu.be,WHiTelist
  - MATCH,WHiTelist
# FALSE
  - DOMAIN-SUFFIX,cn,blaCKlist
  - DOMAIN-KEYWORD,-cn,blaCKlist
  - MATCH,WHiTelist
`
That's my config.yaml, it's wrong or right? If it's right, why can't work in clash because it's working in v2ray-core for linux?
Thanks a lot.

**Comment by Dreamacro** [comment]
@matreex  what if `skip-cert-verify` is true?

**Comment by matreex** [comment]
@Dreamacro `skip-cert-verify` is true, the config.yaml is not working in clash. I don't know why.

**Comment by Dreamacro** [comment]
@matreex What is the version of clash? What does the log look like

**Comment by matreex** [comment]
@Dreamacro waiting, i'll upload it.

**Comment by Dreamacro** [comment]
@matreex 看 https://github.com/Dreamacro/clash/wiki/Breaking-Changes-in-1.0.0

**Comment by matreex** [comment]
@Dreamacro Boom! I see. Thank u so much, trojan is working in clash when had changed `Proxy, Proxy Group and Rule` to `proxies, proxy-groups and rules.` But vmess is not still woking. Can you help to me, again?
https://paste2.org/m3mMvzmM
So... what's the `tls-hostname`, is it validity on clash v1.0.0?

**Comment by Dreamacro** [comment]
@matreex `rules` instead of `Rules`, and plz don't put your proxy to public. In vmess ws mode, set `Host` in ws-headers also set `tls-hostname`

**Comment by matreex** [comment]
![](https://images2.imgbox.com/c2/12/kwBCrOOr_o.png)
About config, we are supposing to work on v2ray-core for linux, but not work clash for linux. (clash v1.0.0)
I want to ask: "
how to close the mux for clash? mux: false or mux: -1.
"network", "security" with "ws", "tls" and "allowInsecure" is true on v2ray-core, so... in clash, skip-cert-verify is only true, that's it?
how to be enable about "connectionReuse" in "wssettings" for clash?
"serverName" with "tlssettings" on v2ray, if it converted to config of clash, tlshostname: www.328du82i.xyz or sni: www.328du82i.xyz."
done.
Thank a lot for you. :P

**Comment by Dreamacro** [comment]
clash not implemented `mux` and `connectionReuse` on vmess, `skip-cert-verify` equal `allowInsecure`. `servername` and `Host` in ws-headers equal `serverName`

**Comment by matreex** [comment]
@Dreamacro I'll try again, thanks.

**Comment by frankang** [comment]
> 支持啊我用的好好的，你自己检查一下配置吧

可以发一下配置吗？我按照下面配置的服务，https://guide.v2fly.org/advanced/tls.html#%E5%AE%A2%E6%88%B7%E7%AB%AF
下面是我在clash的配置，但就是连不上。
```
proxies:
- name: "xyz"
  type: vmess
  server: abc.com
  servername: abc.com
  port: 443
  uuid: uuid
  alterId: 8
  cipher: auto
  udp: true
  network: tcp
  tls: true

```

**Comment by frankang** [comment]
用下面的配置可以了，就是速度不太好。最后还是回到ws+tls的方案

> 

我用 `{ name: "v2ray", type: vmess, server: example.com, port: 443, uuid: UUID, alterId: 0, cipher: none, skip-cert-verify: true, tls: true }` 
是可以正常用tcp+tls的

_Originally posted by @lifansama in https://github.com/vernesong/OpenClash/issues/155#issuecomment-588614277_

**Comment by eromoe** [comment]
能不能自动转换 v2ray 分享码 到clash
