### ISSUE TITLE
Testing Framework

### ISSUE THREAD

**Issue by mayanez** [Dreamacro/clash#962]
Hi,

I'm hoping to get more insight into how Clash is tested. I see a few unit tests, but was wondering if there are any integration type tests? 
Given the multi-platform nature of the project it should be a worthwhile task to take on.

**Comment by Dreamacro** [comment]
For now, only the code of the `common` directory contains unit tests (and tries to get 100% coverage), but the logic of the `application` itself is dynamic, so writing tests for this application logic is hard to maintain. I prefer to write unit tests for more "stable" components. Follow this way, when problems arise, I can eliminate as many of the problems with the basic components as possible.

On the other hand, not all components have the "right baseline", and not all components are easy to test. That's why the unit test is now only being added in `common`.

**Comment by mayanez** [comment]
Cool, makes sense.

How do you currently handle measuring performance across changes? Would this be something you are interested in having?
